const treasureData = [
    {
        id: 1,
        treasure: "Pilze",
        name: "Anisegerling",
        info: "Die Champignons, zu deutsch auch Egerlinge oder Angerlinge, sind eine Pilzgattung aus der Familie der Champignonverwandten. Die Typusart ist der Wiesen-Champignon. ",
        /*Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",*/
        Vorkommen: "Nadel- und Mischwälder, unter Fichten",
        Hut: "vierkantig, Hutrand mit Hautresten",
        Hutfarbe: "weiß, an Druckstellen gelblich",
        Stiel: "1-2 cm dick, weiß mit gelben Flecken, Basis knollig verdickt, doppelter Ring",
        Wuchshöhe: "5-15 cm",
        Fleisch: "weiß, Stiel rosa, nach Anis schmeckend",
        Fruchtkörper: "Mai – Oktober",
        Besonderheit: "essbar",
        Verwechslungsgefahr: "Weiße Giftegerling",
        position: {latitude: 53.5510846, longitude: 9.9936819},
        img: '/images/anisegerling.jpg',
    },
    {
        id: 2,
        treasure: "Pilze",
        name: "Waldegerling",
        info: "Die Champignons, zu deutsch auch Egerlinge oder Angerlinge, sind eine Pilzgattung aus der Familie der Champignonverwandten. Die Typusart ist der Wiesen-Champignon. ",
        /*Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",*/
        Vorkommen: "Nadel- und Mischwälder, unter Fichten",
        Hut: "Durchmesser 5-10 cm, ausgebreitet, braune Schuppen",
        Hutfarbe: "ocker- bis zimtfarben",
        Stiel: "1-1,5 cm dick, weiß, Basis keulig verdickt, vergänglicher Ring",
        Wuchshöhe: "7-10 cm",
        Fleisch: "weiß, nach Holz riechend, an Schnittstellen rot anlaufend",
        Fruchtkörper: "Juli – Oktober",
        Besonderheit: "essbar",
        Verwechslungsgefahr: "Safranschirmling, Kompostegerling, Perlhuhnegerling",
        Verwechslungsgefahr: "Weiße Giftegerling",
        position: {latitude: 53.5510846, longitude: 9.9936819},
        img: '/images/waldegerling.jpg',
    },
    {
        id: 3,
        treasure: "Pilze",
        name: "Birkenröhrling",
        info: "Bei diesen in Deutschland vorkommenden Pilzarten ist der Fruchtkörper in Hut und Stiel unterteilt. An der Hutunterseite sind dicht stehende, feine Röhren, auch als Schwämme bekannt, sichtbar. Sie werden in Dickröhrlingsverwandte (Boletaceae) und Schmierröhrlingsverwandte (Suillaceae) unterteilt. Es gibt kaum giftige und keine tödlich wirkenden Pilze.",
        /*Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",*/
        Vorkommen: "Nadel- und Mischwälder, unter Fichten",
        Hut: "Durchmesser 4-12 cm, leicht gewölbt, oft klebrig",
        Hutfarbe: "samtig nussbraun,",
        Stiel: "grau mit schwarzen Schuppen, Basis etwas verdickt",
        Wuchshöhe: "10-20 cm hoch",
        Fleisch: "fest, weiß bis schwammig",
        Fruchtkörper: "Juni – Oktober",
        Besonderheit: "jung schmackhaft, später weich, schleimig",
        Verwechslungsgefahr: "Braune Rotkappe, Birkenrotkappe",
        position: {latitude: 53.5510846, longitude: 9.9936819},
        img: '/images/birkenröhrling.jpg',
    },
    {
        id: 4,
        treasure: "Pilze",
        name: "Butterröhrling",
        info: "Bei diesen in Deutschland vorkommenden Pilzarten ist der Fruchtkörper in Hut und Stiel unterteilt. An der Hutunterseite sind dicht stehende, feine Röhren, auch als Schwämme bekannt, sichtbar. Sie werden in Dickröhrlingsverwandte (Boletaceae) und Schmierröhrlingsverwandte (Suillaceae) unterteilt. Es gibt kaum giftige und keine tödlich wirkenden Pilze.",
        /*Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",*/
        Vorkommen: "Nadel- und Mischwälder, unter Fichten",
        Hut: "Durchmesser 5-12 cm, halbkugelig, Huthaut klebrig",
        Hutfarbe: "bräunlich-gelb bis schokobraun",
        Stiel: "1-2,5 cm dick, weißlich, beringt",
        Wuchshöhe: "5-10 cm hoch",
        Fleisch: "weich, saftig, säuerlich, gelblich-weiß",
        Fruchtkörper: "Juni – Oktober",
        Besonderheit: "wohlschmeckend, können Allergien verursachen",
        Verwechslungsgefahr: "Goldröhrling, Sandröhrling, Körnchenröhrling",
        position: {latitude: 53.5510846, longitude: 9.9936819},
        img: '/images/butterröhrling.jpg',
    },
    {
        id: 5,
        treasure: "Pilze",
        name: "Flockenstieliger Hexenröhrling",
        info: "Bei diesen in Deutschland vorkommenden Pilzarten ist der Fruchtkörper in Hut und Stiel unterteilt. An der Hutunterseite sind dicht stehende, feine Röhren, auch als Schwämme bekannt, sichtbar. Sie werden in Dickröhrlingsverwandte (Boletaceae) und Schmierröhrlingsverwandte (Suillaceae) unterteilt. Es gibt kaum giftige und keine tödlich wirkenden Pilze.",
        /*Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",*/
        Vorkommen: "Nadel- und Mischwälder, unter Fichten",
        Hut: "Durchmesser 4-20 cm, Huthaut filzig bis samtig",
        Hutfarbe: "mittelbraun bis dunkelbraun",
        Stiel: "3-5 cm dick, keulenförmig bis zylindrisch, gelb mit roten Punkten",
        Wuchshöhe: "5-15 cm",
        Fleisch: "fest, goldgelb, an Schnittstellen blau",
        Fruchtkörper: "Mai – November",
        Besonderheit: "gekocht essbar, roh giftig",
        Verwechslungsgefahr: "Netzstielige Hexenröhrling, Satansröhrling",
        position: {latitude: 53.5510846, longitude: 9.9936819},
        img: '/images/flockenstieligerhexenröhrling.jpg',
    },
    {
        id: 6,
        treasure: "Pilze",
        name: "Kuhröhrling",
        info: "Der Kuh-Röhrling oder Kuhpilz (Suillus bovinus) ist ein essbarer Pilz aus der Familie der Schmierröhrlingsverwandten. Er ist häufig unter Kiefern anzutreffen, mit denen er Mykorrhiza bildet.",
        /*Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",*/
        Vorkommen: "auf sandigen Böden, meist unter Kiefern",
        Hut: "Durchmesser 5-10 cm, halbkugelig bis gewölbt, nasse Huthaut schmierig",
        Hutfarbe: "gelb-, orange- bis olivbraun",
        Stiel: "0,5-2 cm dick, zylindrisch, an Basis zugespitzt, Farbe wie Hut",
        Wuchshöhe: "4-10 cm",
        Fleisch: "zäh, fruchtig, weiß bis hellgelb",
        Fruchtkörper: "Juni – November",
        Besonderheit: "essbar",
        Verwechslungsgefahr: "Körnchenröhrling, Goldröhrling",
        position: {latitude: 53.5510846, longitude: 9.9936819},
        img: '/images/kuhröhrling.jpg',
    },
    {
        id: 7,
        treasure: "Pilze",
        name: "Maronenröhrling",
        info: "Bei diesen in Deutschland vorkommenden Pilzarten ist der Fruchtkörper in Hut und Stiel unterteilt. An der Hutunterseite sind dicht stehende, feine Röhren, auch als Schwämme bekannt, sichtbar. Sie werden in Dickröhrlingsverwandte (Boletaceae) und Schmierröhrlingsverwandte (Suillaceae) unterteilt. Es gibt kaum giftige und keine tödlich wirkenden Pilze.",
        /*Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",*/
        Vorkommen: "hauptsächlich Nadelwälder",
        Hut: "Durchmesser 5-12 cm, Huthaut feinfilzig bis samtig, nass oft schmierig",
        Hutfarbe: "grau bis kastanienfarben, mitunter schwarz oder rotbraun",
        Stiel: "2-5 cm dick, zylindrisch, faserig, zitronengelb bis rotbraun",
        Fleisch: "weiß bis blassgelb, nussigem Geschmack, Schnittstellen blau",
        Fruchtkörper: "Juni – November",
        Besonderheit: "essbar, guter Trockenpilz",
        Verwechslungsgefahr: "Ziegenlippe, Sandröhrling",
        position: {latitude: 53.5510846, longitude: 9.9936819},
        img: '/images/maronenröhrling.jpg',
    },
    {
        id: 8,
        treasure: "Pilze",
        name: "Steinpilz",
        info: "Der Gemeine Steinpilz (Boletus edulis), auch Fichten-Steinpilz, Herrenpilz oder Edelpilz genannt, ist eine Pilzart aus der Familie der Dickröhrlingsverwandten und Typusspezies der Gattung Dickröhrlinge. ",
        /*Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",*/
        Vorkommen: "Nadel- und Mischwälder, unter Fichten",
        Hut: "Durchmesser 8-25 cm, gewölbt",
        Huthaut: "hell- bis dunkelbraun, auch rotbraun, Rand weiß",
        Stiel: "3-6 cm dick, keulenförmig oder zylindrisch, weiß bis hellbraun, helle Netzzeichnung",
        Wuchshöhe: "5-15 cm",
        Fleisch: "fest, weiß, unter Huthaut braun",
        Fruchtkörper: "August – November",
        Besonderheit: "ausgezeichneter Speisepilz",
        Verwechslunsgefahr: "Gallenröhrling, Satansröhrling, Flockenstielige Hexenröhrling",
        position: {latitude: 53.5510846, longitude: 9.9936819},
        img: '/images/steinpilz.jpg',
    },
    {
        id: 9,
        treasure: "Pilze",
        name: "Hellstieliger Filzröhrling",
        info: "Bei diesen in Deutschland vorkommenden Pilzarten ist der Fruchtkörper in Hut und Stiel unterteilt. An der Hutunterseite sind dicht stehende, feine Röhren, auch als Schwämme bekannt, sichtbar. Sie werden in Dickröhrlingsverwandte (Boletaceae) und Schmierröhrlingsverwandte (Suillaceae) unterteilt. Es gibt kaum giftige und keine tödlich wirkenden Pilze.",
        /*Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",*/
        Vorkommen: "Laub- und Nadelwälder",
        Hut: "flach gewölbt, Durchmesser 5-10 cm, Huthaut samtig bis filzig",
        Hutfarbe: "olivgelb bis olivbraun, verblassend",
        Stiel: "1-2 cm dick, in Hutnähe körnig, zylindrisch, rötlich bis bräunlich",
        Wuchshöhe: "4-12 cm",
        Fleisch: "weiß bis gelb, mild, an Schnittstellen schwach blau",
        Fruchtkörper: "Juli – Oktober",
        Besonderheiten: "essbar",
        Verwechslungsgefahr: "Rotfußröhrling",
        position: {latitude: 53.5510846, longitude: 9.9936819},
        img: '/images/hellstieligerfilzröhrling.jpg',
    },
    {
        id: 10,
        treasure: "Pilze",
        name: "Grüner Knollenblätterpilz",
        info: "Der Grüne Knollenblätterpilz oder Grünliche Gift-Wulstling (Amanita phalloides) ist eine Pilzart aus der Familie Amanitaceae, die zur Gattung der Wulstlinge zählt. ",
        /*Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",*/
        Vorkommen: "Nadel- und Mischwälder, unter Fichten",
        Hut: "Durchmesser 5-15 cm, glockig bis flach ausgebreitet",
        Hutfarbe: "von olivgrün über gelb, grau bis graugrün",
        Stiel: "1-2 cm dick, Basis knollig verdickt, weißer Ring vorhanden",
        Wuchshöhe: "6-15 cm",
        Fleisch: "weiß, nach Ammoniak riechend",
        Fruchtkörper: "Juli – November",
        Besonderheiten: "tödlich giftig",
        Verwechslungsgefahr: "Frauentäubling, Grünling",
        position: {latitude: 53.5510846, longitude: 9.9936819},
        img: '/images/grünerknollenblätterpilz.jpg',
    },
    {
        id: 11,
        treasure: "Pilze",
        name: "Pantherpilz",
        info: "Der Pantherpilz (Amanita pantherina) ist eine Pilzart aus der Familie der Wulstlingsverwandten (Amanitaceae). ",
        /*Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",*/
        Vorkommen: "Laub- und Nadelwälder",
        Hut: "Durchmesser 5-15 cm, flach ausgebreitet",
        Hutfarbe: "von ockerfarben über grau- und gelbbraun bis olivbraun, weiße bis graue Velumreste vorhanden",
        Stiel: "0,5-1,5 cm dick, Basis wulstig, gerandete Knolle, weißer Ring vorhanden",
        Wuchshöhe: "5-15 cm",
        Fleisch: "weiß, rettichartiger Geruch",
        Fruchtkörper: "Juli – Oktober",
        Besonderheiten: "sehr giftig",
        Verwechslungsgefahr: "Perlpilz, Gedrungener Wulstling",
        position: {latitude: 53.5510846, longitude: 9.9936819},
        img: '/images/pantherpilz.jpg',
    },
    {
        id: 12,
        treasure: "Pilze",
        name: "Roter Fliegenpilz",
        info: "Der Fliegenpilz (Amanita muscaria), auch Roter Fliegenpilz genannt, ist eine giftige Pilzart aus der Familie der Wulstlingsverwandten. ",
        /*Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",*/
        Vorkommen: "Laub- und Nadelwälder, unter Birken und Fichten",
        Hut: "Durchmesser 5-20 cm, flach ausgebreitet",
        Hutfarbe: "hell- bis dunkelrot, auch orangegelb, weiße oder gelbliche Velumreste vorhanden",
        Stiel: "1-3 cm dick, Basis knollig verdickt, zwei Warzengürtel, weißer oder gelber Ring",
        Wuchshöhe: "10-25 cm",
        Fleisch: "weiß, auch gelb bis orange, mild",
        Fruchtkörper: "August – November",
        Besonderheiten: "giftig, aber nicht tödlich",
        Verwechslungsgefahr: "Kaiserling, in Deutschland selten",
        position: {latitude: 53.5510846, longitude: 9.9936819},
        img: '/images/roterfliegenpilz.jpg',
    },
    {
        id: 13,
        treasure: "Pilze",
        name: "Herbsttrompete",
        info: "Die Toten- oder Herbsttrompete (Craterellus cornucopioides),[1] aufgrund der trichterartig geformten Fruchtkörper auch Toten-Trichterling genannt, ist eine Pilzart aus der Familie der Pfifferlingsverwandten (Cantharellaceae). Sie gilt als sehr guter Speisepilz. ",
        /*Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",*/
        Vorkommen: "hauptsächlich in Laubwäldern, unter Buchen, Eichen und Haselnusssträuchern",
        Form: "Durchmesser 4-10 cm, trichterähnlich, kein Übergang zwischen Hut und Stiel, welliger Rand",
        Farbe: "Innenseite samtig graubraun, Außenseite aschgrau, unten schwarz, reifartig weiß beschlagen",
        Wuchshöhe: "5-12 cm hoch",
        Fleisch: "elastisch, später zäh, sehr würzig",
        Fruchtkörper: "August – November",
        Besonderheiten: "essbar, guter Trockenpilz",
        Verwechslungsgefahr: "Grauer Leistling, Schwarzer Kelchpilz",
        position: {latitude: 53.5510846, longitude: 9.9936819},
        img: '/images/herbsttrompete.jpg',
    },
    {
        id: 14,
        treasure: "Pilze",
        name: "Pfifferling",
        info:"Die Pfifferlinge (Cantharellus) sind eine Pilzgattung aus der Familie der Pfifferlingsverwandten (Cantharellaceae). Die Typusart ist der Echte Pfifferling (Cantharellus cibarius).",
        /*Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",*/
        Vorkommen: "Laub- und Nadelwälder",
        Hut: "trichterartig vertieft, Durchmesser 2-12 cm, Rand wellig",
        Hutfarbe: "hell- bis dottergelb",
        Stiel: "1-2 cm dick, Basis verjüngt, gelb",
        Wuchshöhe: "3-6 cm",
        Fleisch: "weiß, unter Huthaut gelb, pfirsichartiger Geruch",
        Fruchtkörper: "Juni – Oktober",
        Besonderheiten: "essbar",
        Verwechslungsgefahr: "Falscher Pfifferling",
        position: {latitude: 53.5510846, longitude: 9.9936819},
        img: '/images/pfifferling.jpg',
    },
    {
        id: 15,
        treasure: "Pilze",
        name: "Erdritterling",
        info: "Der Gemeine Erd-Ritterling (Tricholoma terreum) ist ein Blätterpilz aus der Familie der Ritterlingsverwandten (Tricholomataceae). ",
        /*Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",*/
        Vorkommen: "Nadelwälder, hauptsächlich Kiefernwälder",
        Hut: "Durchmesser 3-8 cm, ausgebreitet, gebuckelt, Huthaut matt, faserig und feinschuppig",
        Hutfarbe: "schiefer- bis dunkelgrau, nahezu schwarz",
        Stiel: "0,8-1,5 cm dick, weiß bis grauweiß",
        Wuchshöhe: "4-8 cm",
        Fleisch: "sehr dünn, grauweiß, geruchlos",
        Fruchtkörper: "August – November/Dezember",
        Besonderheiten: "essbar",
        Verwechslungsgefahr: "Tigerritterling",
        position: {latitude: 53.5510846, longitude: 9.9936819},
        img: '/images/erdritterling.jpg',
    },
    {
        id: 16,
        treasure: "Pilze",
        name: "Maipilz",
        info: "Der Maipilz (Calocybe gambosa), auch Mai- oder Georgsritterling genannt, ist eine Pilzart aus der Familie der Raslingsverwandten (Lyophyllaceae). ",
        /*Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",*/
        Vorkommen: "grasige Stellen im Wald, Wiesen, Gärten, Parks",
        Hut: "Durchmesser 3-10 cm, ausgebreitet und gebuckelt",
        Hutfarbe: "weiß, cremefarben, grau oder gelblich",
        Stiel: "1,5-4 cm dick, rötlich bis leicht bräunlich",
        Wuchshöhe: "4-9 cm",
        Fleisch: "fest, saftig, weiß, mehlartiger- bis gurkenartiger Geruch",
        Fruchtkörper: "April – Juni",
        Besonderheiten: "essbar",
        Verwechslungsgefahr: "Feldtrichterling, Mairisspilz",
        position: {latitude: 53.5510846, longitude: 9.9936819},
        img: '/images/maipilz.jpg',
    },
    {
        id: 17,
        treasure: "Pilze",
        name: "Schwefelritterling",
        info: "Der Gemeine Schwefel-Ritterling (Tricholoma sulphureum) ist eine Pilzart aus der Familie der Ritterlingsverwandten, die in Laub- und Nadelwäldern Europas, Chinas und Nordamerikas vorkommt. ",
        /*Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",*/
        Vorkommen: "Laubwälder, unter Buchen und Eichen",
        Hut: "Durchmesser 2-7 cm, abgeflacht und gebuckelt, samtig bis faserige Huthaut",
        Hutfarbe: "schwefelgelb, in Mitte bräunlich oder dunkeloliv",
        Stiel: "0,5-1,5 cm dick, zylindrisch bis keulig, bräunlich, hohl",
        Wuchshöhe: "4-8 cm",
        Fleisch: "schwefelgelb, gasartiger Geruch",
        Fruchtkörper: "August – Oktober",
        Besonderheiten: "roh giftig, gekocht ungenießbar",
        Verwechslungsgefahr: "Grünling",
        position: {latitude: 53.5510846, longitude: 9.9936819},
        img: '/images/schwefelritterling.jpg',
    },
    {
        id: 18,
        treasure: "Pilze",
        name: "Riesenschirmpilz",
        info: "Der Gemeine Riesenschirmling, Parasol oder Riesenschirmpilz (Macrolepiota procera) ist eine Pilzart aus der Familie der Champignonverwandten (Agaricaceae). ",
        /*Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",*/
        Vorkommen: "Waldwiesen, Kahlschläge, Wald- und Wegränder",
        Hut: "Durchmesser 10-30 cm, Oberfläche schuppig, sparrig aufreißend, mittig stumpfer Buckel",
        Hutfarbe: "nussbraun bis ockerfarben",
        Stiel: "1-2 cm dick, genattert, hohl, Basis knollig, verschiebbarer Ring",
        Wuchshöhe: "20-40 cm",
        Fleisch: "weiß, weich, Stiel holzig, nussartiger Geschmack",
        Fruchtkörper: "Juli – November",
        Besonderheiten: "essbar",
        Verwechslungsgefahr: "Safranschirmling",
        position: {latitude: 53.5510846, longitude: 9.9936819},
        img: '/images/riesenschirmpilz.jpg',
    },
    {
        id: 19,
        treasure: "Pilze",
        name: "Frauentäubling",
        info: "Der (Violettgrüne) Frauen-Täubling (Russula cyanoxantha) ist eine Pilzart aus der Familie der Täublingsverwandten. ",
        /*Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",*/
        Vorkommen: "Laubwälder, vorzugsweise unter Buchen und Eichen",
        Hut: "Durchmesser 5-18 cm, ausgebreitet, niedergedrückt",
        Hutfarbe: "von schiefergrau über violett bis grün, ockergelb, bläulich, bräunlich oder schwarzviolett",
        Stiel: "2-3 cm dick, meist schwammig, leicht violett bis rötlich",
        Wuchshöhe: "4-12 cm",
        Fleisch: "weiß, unter Huthaut rötlich",
        Fruchtkörper: "Juni – November",
        Besonderheiten: "essbar",
        Verwechslungsgefahr: "Grüner Knollenblätterpilz",
        position: {latitude: 53.5510846, longitude: 9.9936819},
        img: '/images/frauentäubling.jpg',
    },
    {
        id: 20,
        treasure: "Pilze",
        name: "Speisetäubling",
        info: "Der sehr häufige Fleischrote Speise-Täubling (Russula vesca)[1] ist eine Pilzart aus der Familie der Täublingsverwandten (Russulaceae) und ein sehr beliebter Speisepilz.",
        /*Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",*/
        Vorkommen: "Laubwälder, unter Buchen und Eichen",
        Hut: "Durchmesser 6-12 cm, ausgebreitet bis niedergedrückt",
        Hutfarbe: "fleischrot, auch braunrot oder violett, graufleckig",
        Stiel: "1-3 cm dick, zylindrisch, brüchig, weiß",
        Wuchshöhe: "3-8 cm",
        Fleisch: "weiß, oft gelbe bis bräunliche Flecken",
        Fruchtkörper: "Juni – Oktober",
        Besonderheiten: "essbar",
        Verwechslungsgefahr: "Speitäubling, Heringstäubling",
        position: {latitude: 53.5510846, longitude: 9.9936819},
        img: '/images/speisetäubling.jpg',
    },
    {
        id: 21,
        treasure: "Pilze",
        name: "Speitäubling",
        info: "Der Kirschrote Spei-Täubling (Russula emetica) ist ein Blätterpilz aus der Familie der Täublingsverwandten (Russulaceae) und die Typusart der Gattung Russula. ",
        /*Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",*/
        Vorkommen: "feuchte Laub- und Nadelwälder",
        Hut: "Durchmesser 4-10 cm, flach ausgebreitet, niedergedrückt",
        Hutfarbe: "leuchtend rot",
        Stiel: "1-2 cm dick, weiß, Basis rosafleckig, hohl, keulig verdickt",
        Wuchshöhe: "3-10 cm",
        Fleisch: "weiß, unter Huthaut rötlich, brüchig",
        Fruchtkörper: "Juli – November",
        Besonderheiten: "giftig, verursacht Verdauungsstörungen",
        Verwechslungsgefahr: "Apfeltäubling, Heringstäubling",
        position: {latitude: 53.5510846, longitude: 9.9936819},
        img: '/images/speitäubling.jpg',
    },
    {
        id: 22,
        treasure: "Pilze",
        name: "Nebelkappe",
        info: "Der Nebelgraue Trichterling, die Nebel- oder Graukappe (Clitocybe nebularis, syn. Lepista nebularis) ist eine sehr häufige Pilzart aus der Familie der Ritterlingsverwandten. Weitere deutsche Namen sind Graukopf, Herbstblattl oder Nebelgrauer Röteltrichterling. ",
        /*Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",*/
        Vorkommen: "Laub- und Nadelwälder, oft in Reihen oder Ringen stehend",
        Hut: "Durchmesser 6-18 cm, ausgebreitet, niedergedrückt",
        Hutfarbe: "grau, graubraun, weißlich bereift",
        Stiel: "1,5-4 cm dick, weiß bis hellgrau, Basis keulig verdickt",
        Wuchshöhe: "6-10 cm",
        Fleisch: "weiß, süßlicher Milchgeruch",
        Fruchtkörper: "September – November",
        Besonderheiten: "essbar, gut kochen",
        Verwechslungsgefahr: "Riesenrötling",
        position: {latitude: 53.5510846, longitude: 9.9936819},
        img: '/images/nebelkappe.jpg',
    },


    

    /* TIERE TIERE TIERE TIERE TIERE TIERE TIERE TIERE */

    {
        id: 23,
        treasure: "Tiere",
        name: "Haselmaus",
        info: "Die Haselmaus ist keine Maus im eigentlichen Sinne sondern der kleinste Vertreter europäischer Bilche. Auch die größeren Arten Siebenschläfer, Gartenschläfer und Baumschläfer gehören zur Gruppe der Bilche. Typisch für sie alle ist ein langer Winterschlaf. Durch ihre versteckte Lebensweise in der Dunkelheit können Haselmäuse kaum beobachtet werden.",
        location: "location",
        img: '/images/haselmaus2.jpg',
    },
    {
        id: 24,
        treasure: "Tiere",
        name: "Feldhamster",
        info: "Der Feldhamster ist die einzige Art der Gattung Hamster in Europa und etwa so groß wie ein Meerschweinchen. Er legt einen weit verzweigten Bau unter dem Acker an. Der hübsche Nager ernährt sich von Getreide und anderen Feldfrüchten und hält von circa Oktober bis April einen festen Winterschlaf. Ein enger Verwandter ist der Syrische Goldhamster, von dem das beliebte Haustier abstammt.",
        location: "location",
        img: '/images/feldhamster2.jpg',
    },
    {
        id: 25,
        treasure: "Tiere",
        name: "Fledermäuse",
        info: "Fledermäuse üben eine besondere Faszination auf uns Menschen aus! Kein Wunder, die kleinen Säugetiere können vieles, was einzigartig ist: Sie sehen mit den Ohren, fliegen mit den Händen und schlafen mit dem Kopf nach unten. Und nein, sie trinken nicht unser Blut und sind auch nicht angriffslustig, solange sie nicht bedroht werden! Alle der in Deutschland vorkommenden Fledermausarten stehen auf der Roten Liste und sind teilweise vom Aussterben bedroht.",
        location: "location",
        img: '/images/fledermaus2jpg',
    },
    {
        id: 26,
        treasure: "Tiere",
        name: "Gämse",
        info: "Die Gämse ist ein Wiederkäuer und gehört zur Familie der Hornträger (Bovidae). Die Gämse lebt in Gebirgslandschaften und zieht im Sommer auf Hochlagen bis zu 2.500 m. In Deutschland kommt sie in den Alpen und in geringer Zahl auch im Schwarzwald und der Schwäbischen Alb vor. Die Gämse ist laut Gesetz eine jagdbare Art. Der Jäger bezeichnet die Gämse auch als Gams oder in ihrer Mehrzahl als Gamswild.",
        location: "location",
        img: '/images/gämse2.jpg',
    },

    {
        id: 27,
        treasure: "Tiere",
        name: "Rothirsch",
        info: "Das Rotwild ist Deutschlands größte Hirschart und kommt auf etwa 25 % der Bundesfläche vor. In vielen Bundesländern darf der Rothirsch nur in gesetzlich ausgewiesenen Rotwildbezirken leben. Mit der Online-Petition Freiheit für den Rothirsch kämpfen wir für mehr Lebensraum! Die meiste Zeit des Jahres lebt Rotwild äußerst sozial in Rudeln. Nur zur Brunft im September röhren die Hirsche um die Wette und kämpfen mit ihren Geweihen, um Anspruch auf die Weibchen zu erheben. Wie fast alle Hirscharten tragen nur die männlichen Tiere ein Geweih, das jährlich gewechselt wird. In vielen Bundesländern darf der Rothirsch nur in gesetzlich ausgewiesenen Rotwildbezirken leben.",
        location: "location",
        img: '/images/rothirsch.jpg',
    },

    {
        id: 28,
        treasure: "Tiere",
        name: "Feldhase",
        info: "Der Feldhase ist ein faszinierendes Tier: Er ist nicht nur ein Meister der Tarnung mit einem ausgezeichneten Gehör, sondern auch ein exzellenter Sprinter mit einer ausgefeilten Fluchttechnik, den so schnell keiner einholt. Doch leider macht insbesondere die Intensivierung der Landwirtschaft und die Zerschneidung der Landschaft dem Feldhasen das Leben schwer.",
        location: "location",
        img: '/images/feldhase.jpg',
    },

    {
        id: 29,
        treasure: "Tiere",
        name: "Reh",
        info: "Das Reh ist die in Europa häufigste und kleinste Art der Hirsche. Als sogenannter „Trughirsch“ ist es näher mit dem Elch verwandt als mit dem bei uns heimischen Rot- oder Damhirsch. Ursprünglich besiedelten Rehe die Randzonen von Wäldern und Gebüschen, heute kommt es aber in allen Wäldern und sogar in der offenen, fast deckungslosen Feldflur vor.",
        location: "location",
        img: '/images/reh.jpg',
    },

    {
        id: 30,
        treasure: "Tiere",
        name: "Eichhörnchen",
        info: "Eichhörnchen leben in Nadel-, Laub- und Mischwäldern mit alten Baumbeständen und sind fast in ganz Europa verbreitet. In Deutschland und vielen anderen Ländern haben sie sich zum Kulturfolger entwickelt. Sie halten sich gern in der Nähe der Menschen auf und sind in Städten, Gärten und Parks zu finden, solange es dort genügend Nahrung und Unterschlupf gibt. Eichhörnchen halten keinen Winterschlaf sondern Winterruhe und legen im Herbst Vorräte für die kalte Jahreszeit an, indem sie Nüsse und Samen im Boden verstecken.",
        location: "location",
        img: '/images/eichhörnchen.jpg',
    },


    /* BÄUME BÄUME BÄUME BÄUME BÄUME BÄUME */

    {
        id: 9,
        treasure: "Bäume",
        name: "Eiche",
        Merkmale: "Baum Rinde Größe",
        Hutfarbe: "Baumbraun",
        location: "location",
        img: '/images/wald5.jpg',
    },
    {
        id: 10,
        treasure: "Bäume",
        name: "Buche",
        Merkmale: "Baum Rinde Größe",
        Hutfarbe: "Baumbraun",
        location: "location",
        img: '/images/wald6.jpg',
    },
    {
        id: 11,
        treasure: "Bäume",
        name: "Birke",
        Merkmale: "Baum Rinde Größe",
        Hutfarbe: "Baumbraun",
        location: "location",
        img: '/images/wald7.jpg',
    },
    {
        id: 12,
        treasure: "Bäume",
        name: "Kiefer",
        Merkmale: "Baum Rinde Größe",
        Hutfarbe: "Baumbraun",
        location: "location",
        img: '/images/heide1.jpg',
    },

    /* KRÄUTER KRÄUTER KRÄUTER KRÄUTER KRÄUTER KRÄUTER */

    {
        id: 13,
        treasure: "Kräuter",
        name: "Bärlauch",
        Merkmale: "Baum Rinde Größe",
        location: "location",
        img: '/images/heide2.jpg',
    },
    {
        id: 14,
        treasure: "Kräuter",
        name: "Salbei",
        Merkmale: "Baum Rinde Größe",
        location: "location",
        img: '/images/heide3.jpg',
    },
    {
        id: 15,
        treasure: "Kräuter",
        name: "Sauerampfer",
        Merkmale: "Baum Rinde Größe",
        location: "location",
        img: '/images/tiere1.jpg',
    },
    {
        id: 16,
        treasure: "Kräuter",
        name: "Rosmarin",
        Merkmale: "Baum Rinde Größe",
        location: "location",
        img: '/images/tiere2.jpg',
    },

    /* MOORE MOORE MOORE MOORE MOORE MOORE MOORE */


    {
        id: 17,
        treasure: "Moore",
        name: "Wittmoor",
        Merkmale: "Baum Rinde Größe",
        location: "location",
        img: '/images/tiere2.jpg',
    },
    {
        id: 18,
        treasure: "Moore",
        name: "Schnaakenmoor",
        Merkmale: "Baum Rinde Größe",
        location: "location",
        img: '/images/tiere2.jpg',
    },
    {
        id: 19,
        treasure: "Moore",
        name: "Schnaakenmoor",
        Merkmale: "Baum Rinde Größe",
        location: "location",
        img: '/images/tiere2.jpg',
    },
    {
        id: 20,
        treasure: "Moore",
        name: "Schnaakenmoor",
        Merkmale: "Baum Rinde Größe",
        location: "location",
        img: '/images/tiere2.jpg',
    },

    /* SNACKS SNACKS SNACKS SNACKS SNACKS SNACKS SNACKS */

    {
        id: 21,
        treasure: "Snacks",
        name: "Bucheckern",
        location: "location",
        img: '/images/tiere2.jpg',
    },
    {
        id: 22,
        treasure: "Snacks",
        name: "Bucheckern",
        location: "location",
        img: '/images/tiere2.jpg',
    },
    {
        id: 23,
        treasure: "Snacks",
        name: "Bucheckern",
        location: "location",
        img: '/images/tiere2.jpg',
    },
    {
        id: 24,
        treasure: "Snacks",
        name: "Bucheckern",
        location: "location",
        img: '/images/tiere2.jpg',
    },

    /* GEWÄSSER GEWÄSSER GEWÄSSER GEWÄSSER GEWÄSSER GEWÄSSER */


    {
        id: 25,
        treasure: "Gewässer",
        name: "Tümpel",
        location: "location",
        img: '/images/tiere2.jpg',
    },
    {
        id: 26,
        treasure: "Gewässer",
        name: "Tümpel",
        location: "location",
        img: '/images/tiere2.jpg',
    },
    {
        id: 27,
        treasure: "Gewässer",
        name: "Tümpel",
        location: "location",
        img: '/images/tiere2.jpg',
    },
    {
        id: 28,
        treasure: "Gewässer",
        name: "Tümpel",
        location: "location",
        img: '/images/tiere2.jpg',
    },


     /* PFLANZEN PFLANZEN PFLANZEN PFLANZEN PFLANZEN PFLANZEN */


     {
        id: 29,
        treasure: "Gewässer",
        name: "Tümpel",
        location: "location",
        img: '/images/tiere2.jpg',
    },
    {
        id: 30,
        treasure: "Gewässer",
        name: "Tümpel",
        location: "location",
        img: '/images/tiere2.jpg',
    },
    {
        id: 31,
        treasure: "Gewässer",
        name: "Tümpel",
        location: "location",
        img: '/images/tiere2.jpg',
    },
    {
        id: 32,
        treasure: "Gewässer",
        name: "Tümpel",
        location: "location",
        img: '/images/tiere2.jpg',
    },
]

export default treasureData