const TreasureData = [
    {
        id: 1,
        treasure: "Pilze",
        name: "Steinpilz",
        Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",
        Hutfarbe: "Gelb bis orange.",
        Stielfarbe: "Gelb.",
        location: "location",
        img: '../images/person1.jpg',
    },
    {
        id: 2,
        treasure: "Pilze",
        name: "Fliegenpilz",
        Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",
        Hutfarbe: "Gelb bis orange.",
        Stielfarbe: "Gelb.",
        location: "location",
        img: '../images/person2.jpg',
    },
    {
        id: 3,
        treasure: "Pilze",
        name: "Pfifferling",
        Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",
        Hutfarbe: "Gelb bis orange.",
        Stielfarbe: "Gelb.",
        location: "location",
        img: '../images/person3.jpg',
    },
    {
        id: 4,
        treasure: "Pilze",
        name: "Morchel",
        Merkmale: "3 - 6cm breiter mit Schuppen übersäter Hut.",
        Hutfarbe: "Gelb bis orange.",
        Stielfarbe: "Gelb.",
        location: "location",
        img: '../images/baum1.jpg',
    },
    {
        id: 5,
        treasure: "Tiere",
        name: "Schwan",
        Merkmale: "Der gemeine Waldschwan ist ein possierliches Tierchen",
        Hutfarbe: "Trägt für gewöhnlich Sonntags einen Förster-Hut",
        Stielfarbe: "Weiß für gewöhnlich",
        location: "location",
        img: '../images/wald1.jpg',
    },
    {
        id: 6,
        treasure: "Tiere",
        name: "Reh",
        Merkmale: "Bambi is one the run",
        Hutfarbe: "Rekitzchen",
        Stielfarbe: "Weiß für gewöhnlich",
        location: "location",
        img: '../images/wald2.jpg',
    },
    {
        id: 7,
        treasure: "Tiere",
        name: "Hirsch",
        Merkmale: "Hirsch is one the run",
        Hutfarbe: "Der röhrende Hirsch",
        Stielfarbe: "Weiß für gewöhnlich",
        location: "location",
        img: '../images/wald3.jpg',
    },
    {
        id: 8,
        treasure: "Tiere",
        name: "Wildschwein",
        Merkmale: "Wildschwein is one the run",
        Hutfarbe: "Der röhrende Hirsch",
        Stielfarbe: "Weiß für gewöhnlich",
        location: "location",
        img: '../images/wald4.jpg',
    },
    {
        id: 9,
        treasure: "Bäume",
        name: "Eiche",
        Merkmale: "Baum Rinde Größe",
        Hutfarbe: "Baumbraun",
        location: "location",
        img: '../images/wald5.jpg',
    },
    {
        id: 10,
        treasure: "Bäume",
        name: "Buche",
        Merkmale: "Baum Rinde Größe",
        Hutfarbe: "Baumbraun",
        location: "location",
        img: '../images/wald6.jpg',
    },
    {
        id: 11,
        treasure: "Bäume",
        name: "Birke",
        Merkmale: "Baum Rinde Größe",
        Hutfarbe: "Baumbraun",
        location: "location",
        img: '../images/wald7.jpg',
    },
    {
        id: 12,
        treasure: "Bäume",
        name: "Kiefer",
        Merkmale: "Baum Rinde Größe",
        Hutfarbe: "Baumbraun",
        location: "location",
        img: '../images/heide1.jpg',
    },
    {
        id: 13,
        treasure: "Kräuter",
        name: "Bärlauch",
        Merkmale: "Baum Rinde Größe",
        location: "location",
        img: '../images/heide2.jpg',
    },
    {
        id: 14,
        treasure: "Kräuter",
        name: "Salbei",
        Merkmale: "Baum Rinde Größe",
        location: "location",
        img: '../images/heide3.jpg',
    },
    {
        id: 15,
        treasure: "Kräuter",
        name: "Sauerampfer",
        Merkmale: "Baum Rinde Größe",
        location: "location",
        img: '../images/tiere1.jpg',
    },
    {
        id: 16,
        treasure: "Kräuter",
        name: "Rosmarin",
        Merkmale: "Baum Rinde Größe",
        location: "location",
        img: '../images/tiere2.jpg',
    },
    {
        id: 17,
        treasure: "Moore",
        name: "Wittmoor",
        Merkmale: "Baum Rinde Größe",
        location: "location",
        img: '../images/tiere2.jpg',
    },
    {
        id: 18,
        treasure: "Moore",
        name: "Schnaakenmoor",
        Merkmale: "Baum Rinde Größe",
        location: "location",
        img: '../images/tiere2.jpg',
    },
    {
        id: 19,
        treasure: "Moore",
        name: "Schnaakenmoor",
        Merkmale: "Baum Rinde Größe",
        location: "location",
        img: '../images/tiere2.jpg',
    },
    {
        id: 20,
        treasure: "Moore",
        name: "Schnaakenmoor",
        Merkmale: "Baum Rinde Größe",
        location: "location",
        img: '../images/tiere2.jpg',
    },
    {
        id: 21,
        treasure: "Snacks",
        name: "Bucheckern",
        location: "location",
        img: '../images/tiere2.jpg',
    },
    {
        id: 22,
        treasure: "Snacks",
        name: "Bucheckern",
        location: "location",
        img: '../images/tiere2.jpg',
    },
    {
        id: 23,
        treasure: "Snacks",
        name: "Bucheckern",
        location: "location",
        img: '../images/tiere2.jpg',
    },
    {
        id: 24,
        treasure: "Snacks",
        name: "Bucheckern",
        location: "location",
        img: '../images/tiere2.jpg',
    },
    {
        id: 25,
        treasure: "Gewässer",
        name: "Tümpel",
        location: "location",
        img: '../images/tiere2.jpg',
    },
    {
        id: 26,
        treasure: "Gewässer",
        name: "Tümpel",
        location: "location",
        img: '../images/tiere2.jpg',
    },
    {
        id: 27,
        treasure: "Gewässer",
        name: "Tümpel",
        location: "location",
        img: '../images/tiere2.jpg',
    },
    {
        id: 28,
        treasure: "Gewässer",
        name: "Tümpel",
        location: "location",
        img: '../images/tiere2.jpg',
    },
]

export default TreasureData